import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import NavigationBar from '@/components/common/NavigationBar';
import RecoilRootProvider from '@/providers/RecoilRootProvider';
import Providers from '@/providers/NextUiProvider';
import ReactQueryProviders from '@/providers/ReactQueryProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '마이트로피',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <RecoilRootProvider>
          <Providers>
            <ReactQueryProviders>
              <NavigationBar />
              {children}
            </ReactQueryProviders>
          </Providers>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
